site_name: Abyss
site_description: Accelerate your life with an AI launchpad
site_url: https://abyss-app-dev.github.io/docsite/

repo_name: abyss-app-dev/docsite
repo_url: https://github.com/abyss-app-dev/docsite

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github
  # If you have a custom logo, uncomment and update the path below:
  # logo: assets/images/logo.png
  # favicon: assets/images/favicon.png

nav:
  - Home: index.md
  - Documentation:
    - Getting Started: docs/getting-started.md
    - Installation: docs/installation.md
    - User Guide: 
      - Overview: docs/user-guide.md
      - Core Features:
        - Chat Interface: docs/features/chat.md
        - Code Generation: docs/features/code-generation.md
        - Content Creation: docs/features/content-creation.md
        - Data Analysis: docs/features/data-analysis.md
      - Advanced Usage:
        - Workspaces: docs/advanced/workspaces.md
        - Plugins: docs/advanced/plugins.md
        - Automation: docs/advanced/automation.md
    - API Reference: docs/api-reference.md
    - Troubleshooting:
      - Common Issues: docs/troubleshooting/common-issues.md
      - Performance: docs/troubleshooting/performance.md
      - Support: docs/troubleshooting/support.md
  - Release Log: release-log.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abyss-app-dev/docsite
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/abyss_ai
  generator: false

copyright: Copyright &copy; 2024 Abyss Project 